<?php

namespace frontend\modules\neweggcanada\controllers;

use yii\web\Controller;
// use frontend\modules\neweggcanada\components\Validation;
use frontend\modules\neweggcanada\components\Data;
use frontend\modules\neweggcanada\models\NeweggShopDetail;
use yii\helpers\BaseJson;
use Yii;


class NeweggMainController extends Controller
{

    /*
    status for newegg marketplace
    */

    /**
     * Check request authentication
     * @return user status
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub]

        if(property_exists(Yii::$app->errorHandler, 'errorAction'))
        {
            Yii::$app->errorHandler->errorAction = '/neweggcanada/site/neweggerror';
            Yii::$app->errorHandler->errorView =  __DIR__ . '/../views/errorHandler/errorNexception.php';
            Yii::$app->errorHandler->exceptionView = __DIR__ . '/../views/errorHandler/errorNexception.php';
        }

    }

    public function beforeAction($action)
    {
        $current_date = date('Y-m-d H:i:s'); // current date-time
        if (!Yii::$app->user->isGuest) {
            $merchant_id = Yii::$app->user->id; // current users merchant_id
            $data = Data::sqlRecords("SELECT * FROM `newegg_can_shop_detail` WHERE merchant_id='" . $merchant_id . "'", 'one');
            define("MERCHANT_ID", $merchant_id);
            define("SHOP", $data['shop_url']);
            define("TOKEN", $data['token']);
            define("CURRENCY", $data['currency']);
            define("COUNTRY_CODE", $data['country_code']);
            define("EMAIL", $data['email']);
             $neweggConfig=[];
                $neweggConfig = Data::sqlRecords("SELECT `seller_id`,`authorization`,`secret_key` FROM `newegg_can_configuration` WHERE merchant_id='".MERCHANT_ID."'", 'one');
                if($neweggConfig)
                {
                    define("SELLER_ID",$neweggConfig['seller_id']);
                    define("AUTHORIZATION",$neweggConfig['authorization']);
                    define("SECRET_KEY",$neweggConfig['secret_key']);
                    define("API_URL",'https://api.newegg.com/marketplace/can');
                }else{
                    $msg='Please activate newegg api(s) to start integration with Newegg';
                    Yii::$app->session->setFlash('error', $msg);
                    $this->redirect(Data::getUrl('site/index'));
                    return false;
                }
        }
        else{
            $this->redirect(Yii::$app->getUrlManager()->getBaseUrl().'/neweggcanada/site/login',302);
            return false;
        }


        if (!empty($data)) {

            if (strtotime($data['expire_date']) < strtotime($current_date) ) {
                if (isset($data['install_status']) && $data['install_status'] == 0) {
                    /*Yii::$app->user->logout();
                    $this->redirect(Yii::$app->getUrlManager()->getBaseUrl().'/neweggcanada/site/login',302);*/
                    return $this->redirect('https://apps.shopify.com/walmart-marketplace-integration');
                    //return false;
                }
                else{
                    $neweggShopDetailModel = new NeweggShopDetail();
                        $neweggShopDetail = $neweggShopDetailModel->find()->where(['shop_url' => $data['shop_url']])->one();
                        $neweggShopDetail->purchase_status = Data::PURCHASE_STATUS_TRAILEXPIRE;
                        $neweggShopDetail->save(false);
                        $this->redirect(Yii::$app->getUrlManager()->getBaseUrl().'/neweggcanada/site/paymentplan',302);
                        return true;

                }
                return true;
            }
            else if(isset($data['install_status']) && $data['install_status'] == 0){

                return $this->redirect('https://apps.shopify.com/walmart-marketplace-integration');
            }
            else {

                return true;
            }
        } else {
            //redirect login page
            Yii::$app->user->logout();
            $this->redirect(Yii::$app->getUrlManager()->getBaseUrl().'/neweggcanada/site/login',302);
            return false;
        }

        return true;
    }
}
