<?php return $arr = array (
  'Clothing' => 
  array (
    'shortDescription' => 
    array (
      'name' => 'shortDescription',
      'maxOccurs' => '1',
      'minOccurs' => '1',
      'documentation' => 'Overview of the key selling points of the item, marketing content, and highlights in paragraph form. For SEO purposes, repeat the product name and relevant keywords here.',
      'requiredLevel' => 'Required',
      'displayName' => 'Description',
      'group' => 'Basic',
      'rank' => '8000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'keyFeatures' => 
    array (
      'name' => 'keyFeatures',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Key features will appear as bulleted text on the item page and in search results. Key features help the user understand the benefits of the product with a simple and clean format. We highly recommended using three or more key features.',
      'requiredLevel' => 'Recommended',
      'displayName' => 'Key Features',
      'group' => 'Basic',
      'rank' => '9000',
    ),
    'brand' => 
    array (
      'name' => 'brand',
      'maxOccurs' => '1',
      'minOccurs' => '1',
      'documentation' => 'Name, term, design or other feature that distinguishes one seller\'s product from those of others. This can be the name of the company associated with the product, but not always. If item does not have a brand, use "Unbranded".',
      'requiredLevel' => 'Required',
      'displayName' => 'Brand',
      'group' => 'Basic',
      'rank' => '11000',
      'dataType' => 'string',
      'maxLength' => '60',
      'minLength' => '1',
    ),
    'manufacturer' => 
    array (
      'name' => 'manufacturer',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Manufacturer is the maker of the product. This is the name of the company that produces the product, not necessarily the brand name of the item. For some products, the manufacturer and the brand may be the same.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Manufacturer',
      'group' => 'Basic',
      'rank' => '12000',
      'dataType' => 'string',
      'maxLength' => '60',
      'minLength' => '1',
    ),
    'manufacturerPartNumber' => 
    array (
      'name' => 'manufacturerPartNumber',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'MPN uniquely identifies the product to its manufacturer. For many products this will be identical to the model number. Some manufacturers distinguish part number from model number. Having this information allows customers to search for items on the site and informs product matching.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Manufacturer Part Number',
      'group' => 'Basic',
      'rank' => '13000',
      'dataType' => 'string',
      'maxLength' => '60',
      'minLength' => '1',
    ),
    'multipackQuantity' => 
    array (
      'name' => 'multipackQuantity',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'The number of identical, individually packaged-for-sale items. If an item does not contain other items, does not contain identical items, or if the items contained within cannot be sold individually, the value for this attribute should be "1." Examples: (1) A single bottle of 50 pills has a "Multipack Quantity" of "1." (2) A package containing two identical bottles of 50 pills has a "Multipack Quantity" of 2. (3) A 6-pack of soda labelled for individual sale connected by plastic rings has a "Multipack Quantity" of "6." (4) A 6-pack of soda in a box whose cans are not marked for individual sale has a "Multipack Quantity" of "1." (5) A gift basket of 5 different items has a "Multipack Quantity" of "1."',
      'requiredLevel' => 'Recommended',
      'displayName' => 'Multipack Quantity',
      'group' => 'Basic',
      'rank' => '13250',
      'dataType' => 'integer',
      'totalDigits' => '4',
    ),
    'countPerPack' => 
    array (
      'name' => 'countPerPack',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'The number of identical items inside each individual pack given by the "Multipack Quantity" attribute. Examples: (1) A single bottle of 50 pills has a "Count Per Pack" of "50." (2) A package containing two identical bottles of 50 pills has a "Count Per Pack" of 50. (3) A 6-pack of soda labelled for individual sale connected by plastic rings has a "Count Per Pack" of "1." (4) A 6-pack of soda in a box whose cans are not marked for individual sale has a "Count Per Pack" of "6." (5) A gift basket of 5 different items has a "Count Per Pack" of "1."',
      'requiredLevel' => 'Recommended',
      'displayName' => 'Count Per Pack',
      'group' => 'Basic',
      'rank' => '13500',
      'dataType' => 'integer',
      'totalDigits' => '4',
    ),
    'count' => 
    array (
      'name' => 'count',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'The total number of identical items in the package or box; a result of the multiplication of Multipack Quantity by Count Per Pack. Examples: (1) A single bottle of 50 pills has a "Total Count" of 50. (2) A package containing two identical bottles of 50 pills has a "Total Count" of 100. (3) A gift basket of 5 different items has a "Total Count" of 1.',
      'requiredLevel' => 'Recommended',
      'displayName' => 'Total Count',
      'group' => 'Basic',
      'rank' => '13750',
      'dataType' => 'string',
      'maxLength' => '7',
      'minLength' => '1',
    ),
    'pieceCount' => 
    array (
      'name' => 'pieceCount',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'The number of small pieces, slices, or different items within the product. Piece Count applies to things such as puzzles, building block sets, and products that contain multiple different items (such as tool sets, dinnerware sets, gift baskets, art sets, makeup kits, or shaving kits). EXAMPLE: (1) A 500-piece puzzle has a "Piece Count" of 500. (2) A 105-Piece Socket Wrench set has a piece count of "105." (3) A gift basket of 5 different items has a "Piece Count" of 5.',
      'requiredLevel' => 'Recommended',
      'displayName' => 'Number of Pieces',
      'group' => 'Basic',
      'rank' => '13875',
      'dataType' => 'integer',
      'totalDigits' => '20',
    ),
    'modelNumber' => 
    array (
      'name' => 'modelNumber',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Model numbers allow manufacturers to keep track of each hardware device and identify or replace the proper part when needed. Model numbers are often found on the bottom, back, or side of a product. Having this information allows customers to search for items on the site and informs product matching.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Model Number',
      'group' => 'Basic',
      'rank' => '14000',
      'dataType' => 'string',
      'maxLength' => '60',
      'minLength' => '1',
    ),
    'mainImageUrl' => 
    array (
      'name' => 'mainImageUrl',
      'maxOccurs' => '1',
      'minOccurs' => '1',
      'documentation' => 'Main image of the item. Image URL must end in the file name. Image URL must be static and have no redirections. Preferred file type: JPEG Accepted file types: JPG, PNG, GIF, BMP Recommended image resolution: 3000 x 3000 pixels at 300 ppi. Minimum image size requirements: Zoom capability: 2000 x 2000 pixels at 300 ppi. Non-zoom minimum: 500 x 500 pixels at 72 ppi. Maximum file size: 2 MB.',
      'requiredLevel' => 'Required',
      'displayName' => 'Main Image URL',
      'group' => 'Images',
      'rank' => '16000',
      'dataType' => 'anyURI',
    ),
    'productSecondaryImageURL' => 
    array (
      'name' => 'productSecondaryImageURL',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Secondary images of the item. Image URL must end in the file name. Image URL must be static and have no redirections. Preferred file type: JPEG Accepted file types: JPG, PNG, GIF, BMP Recommended image resolution: 3000 x 3000 pixels at 300 ppi. Minimum image size requirements: Zoom capability: 2000 x 2000 pixels at 300 ppi. Non-zoom minimum: 500 x 500 pixels at 72 ppi. Maximum file size: 2 MB.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Additional Image URL',
      'group' => 'Images',
      'rank' => '17000',
    ),
    'color' => 
    array (
      'name' => 'color',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Color as described by the manufacturer.',
      'requiredLevel' => 'Recommended',
      'displayName' => 'Color',
      'group' => 'Discoverability',
      'rank' => '19000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'colorCategory' => 
    array (
      'name' => 'colorCategory',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Select the color from a short list that best describes the general color of the item. This improves searchability as it allows customers to view items by color from the left navigation when they perform a search.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Color Category',
      'group' => 'Discoverability',
      'rank' => '20000',
      'child' => 
      array (
        0 => 
        array (
          'name' => 'colorCategoryValue',
          'maxOccurs' => 'unbounded',
          'minOccurs' => '1',
          'dataType' => 'string',
          'optionValues' => 
          array (
            0 => 'Beige',
            1 => 'Black',
            2 => 'Blue',
            3 => 'Bronze',
            4 => 'Brown',
            5 => 'Clear',
            6 => 'Gold',
            7 => 'Gray',
            8 => 'Green',
            9 => 'Multi-color',
            10 => 'Off-White',
            11 => 'Orange',
            12 => 'Pink',
            13 => 'Purple',
            14 => 'Red',
            15 => 'Silver',
            16 => 'White',
            17 => 'Yellow',
          ),
        ),
      ),
    ),
    'pattern' => 
    array (
      'name' => 'pattern',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Decorative design or visual ornamentation, often with a thematic, recurring motif.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Pattern',
      'group' => 'Discoverability',
      'rank' => '21000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'material' => 
    array (
      'name' => 'material',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'The main material(s) that a product is made of. This does not need to be an exhaustive list, but should contain the predominant or functionally important material/materials. Fabric material specifics should be entered using the "Fabric Content" attribute.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Material',
      'group' => 'Discoverability',
      'rank' => '22000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'gender' => 
    array (
      'name' => 'gender',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Indicate whether this item is meant for a particular gender or meant to be gender-agnostic (unisex).',
      'requiredLevel' => 'Recommended',
      'displayName' => 'Gender',
      'group' => 'Discoverability',
      'rank' => '23000',
      'dataType' => 'string',
      'optionValues' => 
      array (
        0 => 'Male',
        1 => 'Female',
        2 => 'Unisex',
      ),
    ),
    'ageGroup' => 
    array (
      'name' => 'ageGroup',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'General grouping of ages into commonly used demographic labels.',
      'requiredLevel' => 'Recommended',
      'displayName' => 'Age Group',
      'group' => 'Discoverability',
      'rank' => '24000',
      'child' => 
      array (
        0 => 
        array (
          'name' => 'ageGroupValue',
          'maxOccurs' => 'unbounded',
          'minOccurs' => '1',
          'dataType' => 'string',
          'optionValues' => 
          array (
            0 => 'Child',
            1 => 'Tween',
            2 => 'Teen',
            3 => 'Adult',
          ),
        ),
      ),
    ),
    'clothingSizeGroup' => 
    array (
      'name' => 'clothingSizeGroup',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'The common sizing groups used by the retail clothing industry.',
      'requiredLevel' => 'Recommended',
      'displayName' => 'Clothing Size Group',
      'group' => 'Discoverability',
      'rank' => '25000',
      'dataType' => 'string',
      'optionValues' => 
      array (
        0 => 'Big & Tall',
        1 => 'Boys',
        2 => 'Girls',
        3 => 'Girls\' Plus',
        4 => 'Husky',
        5 => 'Junior Plus',
        6 => 'Juniors',
        7 => 'Maternity',
        8 => 'Maternity Plus',
        9 => 'Men',
        10 => 'Petite',
        11 => 'Petite Plus',
        12 => 'Women\'s Plus',
        13 => 'Women',
        14 => 'Young Men’s',
      ),
    ),
    'clothingSize' => 
    array (
      'name' => 'clothingSize',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Clothing size as it appears on the garment label. Use this attribute for general sizes (S, M, L) as well as general numbered sizes (2, 4, 6, etc). For items that have unique sizes (dress shirts, bras, etc.) use the specific size attribute.',
      'requiredLevel' => 'Recommended',
      'displayName' => 'Clothing Size',
      'group' => 'Discoverability',
      'rank' => '26000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'isSet' => 
    array (
      'name' => 'isSet',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Y indicates that the product consists of two or more different items sold together as a set. Example: A bedding set that includes sheets, pillow shams, and a comforter.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Is Set',
      'group' => 'Discoverability',
      'rank' => '28000',
      'dataType' => 'string',
      'optionValues' => 
      array (
        0 => 'Yes',
        1 => 'No',
      ),
    ),
    'variantGroupId' => 
    array (
      'name' => 'variantGroupId',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Required if item is a variant. Make up a number and/or letter code for “Variant Group ID” and add this to all variations of the same product. Partners must ensure uniqueness of their Variant Group IDs.',
      'requiredLevel' => 'Conditionally Required',
      'conditionalAttributes' => 
      array (
        0 => 
        array (
          'name' => 'variantAttributeNames',
          'value' => 'ANY',
        ),
      ),
      'displayName' => 'Variant Group ID',
      'group' => 'Item Variants',
      'rank' => '35000',
      'dataType' => 'string',
      'maxLength' => '300',
      'minLength' => '1',
    ),
    'variantAttributeNames' => 
    array (
      'name' => 'variantAttributeNames',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Designate all attributes by which the item is varying. Variant attributes are limited to those designated for each category. ',
      'requiredLevel' => 'Conditionally Required',
      'conditionalAttributes' => 
      array (
        0 => 
        array (
          'name' => 'variantGroupId',
          'value' => 'ANY',
        ),
      ),
      'displayName' => 'Variant Attribute Names',
      'group' => 'Item Variants',
      'rank' => '36000',
      'child' => 
      array (
        0 => 
        array (
          'name' => 'variantAttributeName',
          'maxOccurs' => 'unbounded',
          'minOccurs' => '1',
          'dataType' => 'string',
          'optionValues' => 
          array (
            0 => 'color',
            1 => 'clothingSize',
            2 => 'clothingFit',
            3 => 'pattern',
            4 => 'material',
            5 => 'inseam',
            6 => 'waistSize',
            7 => 'neckSize',
            8 => 'hatSize',
            9 => 'pantySize',
            10 => 'sockSize',
            11 => 'countPerPack',
            12 => 'count',
            13 => 'braSize',
            14 => 'braBandSize',
            15 => 'braCupSize',
            16 => 'academicInstitution',
            17 => 'accentColor',
            18 => 'sportsTeam',
            19 => 'character',
          ),
        ),
      ),
    ),
    'isPrimaryVariant' => 
    array (
      'name' => 'isPrimaryVariant',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Note whether item is intended as the main variant in a variant grouping. The primary variant will appear as the image when customers search and the first image displayed on the item page. This should be set as "Yes" for only one item in a group of variants.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Is Primary Variant',
      'group' => 'Item Variants',
      'rank' => '37000',
      'dataType' => 'string',
      'optionValues' => 
      array (
        0 => 'Yes',
        1 => 'No',
      ),
    ),
    'isProp65WarningRequired' => 
    array (
      'name' => 'isProp65WarningRequired',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Selecting "Y" indicates the product requires California\'s Proposition 65 special warning. Proposition 65 entitles California consumers to special warnings for products that contain chemicals known to the state of California to cause cancer and birth defects or other reproductive harm if certain criteria are met (such as quantity of chemical contained in the product). See the portions of the California Health and Safety Code related to Proposition 65 for more information.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Is Prop 65 Warning Required',
      'group' => 'Compliance',
      'rank' => '41000',
      'dataType' => 'string',
      'optionValues' => 
      array (
        0 => 'Yes',
        1 => 'No',
      ),
    ),
    'prop65WarningText' => 
    array (
      'name' => 'prop65WarningText',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'This is a particular statement legally required by the State of California for certain products to warn consumers about potential health dangers. See the portions of the California Health and Safety Code related to Proposition 65 to see what products require labels and to verify the text of your warning label.',
      'requiredLevel' => 'Conditionally Required',
      'conditionalAttributes' => 
      array (
        0 => 
        array (
          'name' => 'isProp65WarningRequired',
          'value' => 'Yes',
        ),
      ),
      'displayName' => 'Prop 65 Warning Text',
      'group' => 'Compliance',
      'rank' => '42000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'smallPartsWarnings' => 
    array (
      'name' => 'smallPartsWarnings',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'To determine if any choking warnings are applicable, check current product packaging for choking warning message(s). Please indicate the warning number (0-6). 0 - No warning applicable; 1 - Choking hazard is a small ball; 2 - Choking hazard contains small ball; 3 - Choking hazard contains small parts; 4 - Choking hazard balloon; 5 - Choking hazard is a marble; 6 - Choking hazard contains a marble.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Small Parts Warning Code',
      'group' => 'Compliance',
      'rank' => '43000',
      'child' => 
      array (
        0 => 
        array (
          'name' => 'smallPartsWarning',
          'maxOccurs' => 'unbounded',
          'minOccurs' => '1',
          'dataType' => 'integer',
          'optionValues' => 
          array (
            0 => '0',
            1 => '1',
            2 => '2',
            3 => '3',
            4 => '4',
            5 => '5',
            6 => '6',
          ),
        ),
      ),
    ),
    'requiresTextileActLabeling' => 
    array (
      'name' => 'requiresTextileActLabeling',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Select "Y" if your item contains wool or is one of the following: clothing (except for hats and shoes), handkerchiefs, scarves, bedding (including sheets, covers, blankets, comforters, pillows, pillowcases, quilts, bedspreads and pads (but not outer coverings for mattresses or box springs)), curtains and casements, draperies, tablecloths, napkins, doilies, floor coverings (rugs, carpets and mats), towels, washcloths, dishcloths, ironing board covers and pads, umbrellas, parasols, bats or batting, flags with heading or that are bigger than 216 square inches, cushions, all fibers, yarns and fabrics (but not packaging ribbons), furniture slip covers and other furniture covers, afghans and throws, sleeping bags, antimacassars (doilies), hammocks, dresser and other furniture scarves. For further information on these requirements, refer to the labeling requirements of the Textile Act. ',
      'requiredLevel' => 'Optional',
      'displayName' => 'Requires Textile Act Labeling',
      'group' => 'Compliance',
      'rank' => '44000',
      'dataType' => 'string',
      'optionValues' => 
      array (
        0 => 'Yes',
        1 => 'No',
      ),
    ),
    'countryOfOriginTextiles' => 
    array (
      'name' => 'countryOfOriginTextiles',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Use “Made in U.S.A. and Imported” to indicate manufacture in the U.S. from imported materials, or part processing in the U.S. and part in a foreign country. Use “Made in U.S.A. or Imported” to reflect that some units of an item originate from a domestic source and others from a foreign source. Use “Made in U.S.A.” only if all units were made completely in the U.S. using materials also made in the U.S. Use "Imported" if units are completely imported.',
      'requiredLevel' => 'Conditionally Required',
      'conditionalAttributes' => 
      array (
        0 => 
        array (
          'name' => 'requiresTextileActLabeling',
          'value' => 'Yes',
        ),
      ),
      'displayName' => 'Country of Origin - Textiles',
      'group' => 'Compliance',
      'rank' => '45000',
      'dataType' => 'string',
      'optionValues' => 
      array (
        0 => 'USA',
        1 => 'Imported',
        2 => 'USA and Imported',
        3 => 'USA or Imported',
      ),
    ),
    'batteryTechnologyType' => 
    array (
      'name' => 'batteryTechnologyType',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Please select the Battery Technology Type from the list provided. NOTE: If battery type is lead acid, lead acid (nonspillable), lithium ion, or lithium metal, please ensure that you have obtained a hazardous materials risk assessment through WERCS  before setting up your item. ',
      'requiredLevel' => 'Conditionally Required',
      'conditionalAttributes' => 
      array (
        0 => 
        array (
          'name' => 'hasBatteries',
          'value' => 'Yes',
        ),
      ),
      'displayName' => 'Contained Battery Type',
      'group' => 'Compliance',
      'rank' => '47000',
      'dataType' => 'string',
      'optionValues' => 
      array (
        0 => 'Does Not Contain a Battery',
        1 => 'Alkaline',
        2 => 'Carbon Zinc',
        3 => 'Lead Acid',
        4 => 'Lead Acid (Nonspillable)',
        5 => 'Lithium Primary (Lithium Metal)',
        6 => 'Lithium Ion',
        7 => 'Magnesium',
        8 => 'Mercury',
        9 => 'Nickel Cadmium',
        10 => 'Nickel Metal Hydride',
        11 => 'Silver',
        12 => 'Thermal',
        13 => 'Other',
        14 => 'Multiple Types',
      ),
    ),
    'hasWarranty' => 
    array (
      'name' => 'hasWarranty',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Y indicates the item comes with a warranty. If an item has a warranty, then enter EITHER the warranty URL or the warranty text in the appropriate field.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Has Warranty',
      'group' => 'Compliance',
      'rank' => '48000',
      'dataType' => 'string',
      'optionValues' => 
      array (
        0 => 'Yes',
        1 => 'No',
      ),
    ),
    'warrantyURL' => 
    array (
      'name' => 'warrantyURL',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'If you indicated that your item has a warranty, provide either the Warranty URL or Warranty Text. The Warranty URL is the web location of the image, PDF, or link to the manufacturer\'s warranty page, showing the warranty and its terms, including the duration of the warranty. URLs must begin with http:// or https:// NOTE: Please remember to update the link and/or text of the warranty as the warranty changes. If supplying an image, provide the final destination image URL (no-redirects) that is publicly accessible (no username/password required) and ends in a proper image extension. Recommended file type: JPEG Accepted file types: JPG, PNG, GIF, BMP Maximum file size: 2 GB. If the Ingredients have been included in another image, you may repeat the URL here. ',
      'requiredLevel' => 'Conditionally Required',
      'conditionalAttributes' => 
      array (
        0 => 
        array (
          'name' => 'warrantyText',
          'value' => 'null',
        ),
        1 => 
        array (
          'name' => 'hasWarranty',
          'value' => 'Yes',
        ),
      ),
      'displayName' => 'Warranty URL',
      'group' => 'Compliance',
      'rank' => '49000',
      'dataType' => 'anyURI',
    ),
    'warrantyText' => 
    array (
      'name' => 'warrantyText',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'If you marked Y for "Has Warranty" provide the Warranty URL or Warranty Text (the full text of the warranty terms, including what is covered by the warranty and the duration of the warranty). NOTE: please remember to update the text of your warranty as your warranty changes.',
      'requiredLevel' => 'Conditionally Required',
      'conditionalAttributes' => 
      array (
        0 => 
        array (
          'name' => 'warrantyURL',
          'value' => 'null',
        ),
        1 => 
        array (
          'name' => 'hasWarranty',
          'value' => 'Yes',
        ),
      ),
      'displayName' => 'Warranty Text',
      'group' => 'Compliance',
      'rank' => '50000',
      'dataType' => 'string',
      'maxLength' => '1000',
      'minLength' => '1',
    ),
    'clothingTopStyle' => 
    array (
      'name' => 'clothingTopStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Style terms descriptive of clothing tops.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Clothing Top Style',
      'group' => 'Upper Body Features',
      'rank' => '59000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'dressShirtSize' => 
    array (
      'name' => 'dressShirtSize',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'A grouping of sizes for dress shirts based on collar measurement and sleeve measurement.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Dress Shirt Size',
      'group' => 'Upper Body Features',
      'rank' => '59500',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'sleeveStyle' => 
    array (
      'name' => 'sleeveStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Descriptive terms for the style of garment sleeves. Does not include descriptive terms for sleeve length (which appear under the Sleeve Length Style attribute).',
      'requiredLevel' => 'Optional',
      'displayName' => 'Sleeve Style',
      'group' => 'Upper Body Features',
      'rank' => '62000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'sleeveLengthStyle' => 
    array (
      'name' => 'sleeveLengthStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Descriptive terms for sleeve length.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Sleeve Length Style',
      'group' => 'Upper Body Features',
      'rank' => '63000',
      'dataType' => 'string',
      'optionValues' => 
      array (
        0 => 'Short Sleeve',
        1 => 'Long Sleeve',
        2 => 'Sleeveless',
        3 => '1/4 Sleeve',
        4 => '3/4 Sleeve',
        5 => 'Elbow-Length',
      ),
    ),
    'shirtNeckStyle' => 
    array (
      'name' => 'shirtNeckStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'A garment\'s neckline or neck style.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Clothing Neck Style',
      'group' => 'Upper Body Features',
      'rank' => '64000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'collarType' => 
    array (
      'name' => 'collarType',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Style of collar, as expressed by shape or design.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Collar Style',
      'group' => 'Upper Body Features',
      'rank' => '65000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'jacketStyle' => 
    array (
      'name' => 'jacketStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Styles specific to coats and jackets.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Jacket Style',
      'group' => 'Upper Body Features',
      'rank' => '66000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'suitBreastingStyle' => 
    array (
      'name' => 'suitBreastingStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'The closure style of a suit jacket or coat; double-breasted suits have more fabric where they overlap in front and commonly have 2 rows of buttons.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Suit Breasting Style',
      'group' => 'Upper Body Features',
      'rank' => '67000',
      'dataType' => 'string',
      'optionValues' => 
      array (
        0 => 'double-breasted',
        1 => 'single-breasted',
      ),
    ),
    'sweaterStyle' => 
    array (
      'name' => 'sweaterStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Styles specific to sweaters.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Sweater Style',
      'group' => 'Upper Body Features',
      'rank' => '68000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'scarfStyle' => 
    array (
      'name' => 'scarfStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Styles specific to scarves.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Scarf Style',
      'group' => 'Upper Body Features',
      'rank' => '69000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'upperBodyStrapConfiguration' => 
    array (
      'name' => 'upperBodyStrapConfiguration',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Strap configuration style for bras, swimsuit tops, leotards and other clothing tops.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Upper Body Strap Configuration',
      'group' => 'Upper Body Features',
      'rank' => '70000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'hatSize' => 
    array (
      'name' => 'hatSize',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'The sizing information specific to hats, ranging from 6 1/4 to 8 1/8. Generic sized (small/med/large) hats may not have this information (generic s/m/l size information should be entered under the "Clothing Size" attribute).',
      'requiredLevel' => 'Optional',
      'displayName' => 'Hat Size',
      'group' => 'Upper Body Features',
      'rank' => '71000',
      'dataType' => 'string',
      'optionValues' => 
      array (
        0 => '6 1/4',
        1 => '6 3/8',
        2 => '6 1/2',
        3 => '6 5/8',
        4 => '6 3/4',
        5 => '6 7/8',
        6 => '7',
        7 => '7 1/8',
        8 => '7 1/4',
        9 => '7 3/8',
        10 => '7 1/2',
        11 => '7 5/8',
        12 => '7 3/4',
        13 => '7 7/8',
        14 => '8',
        15 => '8 1/8',
      ),
    ),
    'hatStyle' => 
    array (
      'name' => 'hatStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Styles specific to hats.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Hat Style',
      'group' => 'Upper Body Features',
      'rank' => '72000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'braStyle' => 
    array (
      'name' => 'braStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Brassiere styles/defining features. Enter as many as are relevant to the bra. Do not enter strap styles here. To enter descriptive terms for strap styles, please use the "Upper Body Strap Configuration" attribute.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Bra Style',
      'group' => 'Upper Body Features',
      'rank' => '73000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'braSize' => 
    array (
      'name' => 'braSize',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Bra size, consisting of band and cup. Use this attribute if the garment has both measurements. If the bra has standard clothing sizes (e.g. S, M, L), enter the size under "Clothing Size".  NOTE: for garments that have chest size (measured as the largest part of the chest, i.e. some women\'s slips), use "Chest Size".',
      'requiredLevel' => 'Optional',
      'displayName' => 'Bra Size',
      'group' => 'Upper Body Features',
      'rank' => '74000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'chestSize' => 
    array (
      'name' => 'chestSize',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Chest measurement in inches, around the largest part of the chest. Often used for men\'s jackets and women\'s full slips.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Chest Size',
      'group' => 'Upper Body Features',
      'rank' => '77000',
      'child' => 
      array (
        0 => 
        array (
          'name' => 'measure',
          'maxOccurs' => '1',
          'minOccurs' => '1',
          'dataType' => 'decimal',
          'totalDigits' => '16',
        ),
        1 => 
        array (
          'name' => 'unit',
          'maxOccurs' => '1',
          'minOccurs' => '1',
          'dataType' => 'string',
          'optionValues' => 
          array (
            0 => 'in',
            1 => 'cm',
          ),
        ),
      ),
    ),
    'pantRise' => 
    array (
      'name' => 'pantRise',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'The height at which the waistline rests on the body.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Waist Rise',
      'group' => 'Lower Body Features',
      'rank' => '80000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'waistStyle' => 
    array (
      'name' => 'waistStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Waist styles/defining features.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Waist Style',
      'group' => 'Lower Body Features',
      'rank' => '80500',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'waistSize' => 
    array (
      'name' => 'waistSize',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Waist measurement in inches, around the smallest section of the natural waist (typically located just above the belly button).',
      'requiredLevel' => 'Optional',
      'displayName' => 'Waist Size',
      'group' => 'Lower Body Features',
      'rank' => '80750',
      'child' => 
      array (
        0 => 
        array (
          'name' => 'measure',
          'maxOccurs' => '1',
          'minOccurs' => '1',
          'dataType' => 'decimal',
          'totalDigits' => '16',
        ),
        1 => 
        array (
          'name' => 'unit',
          'maxOccurs' => '1',
          'minOccurs' => '1',
          'dataType' => 'string',
          'optionValues' => 
          array (
            0 => 'in',
          ),
        ),
      ),
    ),
    'pantySize' => 
    array (
      'name' => 'pantySize',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Panty size. Generic sized (small/med/large) panties may not have this information (generic s/m/l size information should be entered under the "Clothing Size" attribute). Clothing size style values (Plus Size, Petite, Juniors, etc) should be entered under the "Clothing Size Style" attribute.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Panty Size',
      'group' => 'Lower Body Features',
      'rank' => '81000',
      'dataType' => 'string',
      'optionValues' => 
      array (
        0 => '0',
        1 => '1',
        2 => '2',
        3 => '3',
        4 => '4',
        5 => '5',
        6 => '6',
        7 => '7',
        8 => '8',
        9 => '9',
        10 => '10',
        11 => '11',
        12 => '12',
        13 => '13',
        14 => '14',
        15 => '15',
        16 => '16',
        17 => '17',
        18 => '18',
        19 => '19',
        20 => '20',
        21 => '21',
        22 => '22',
        23 => '23',
        24 => '24',
        25 => '25',
        26 => '26',
        27 => '27',
        28 => '28',
        29 => '29',
        30 => '30',
        31 => '31',
        32 => '32',
        33 => '33',
        34 => '34',
      ),
    ),
    'skirtLength' => 
    array (
      'name' => 'skirtLength',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'The measurement of the skirt, from waist to bottom hem, in inches.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Skirt Length',
      'group' => 'Lower Body Features',
      'rank' => '82000',
      'child' => 
      array (
        0 => 
        array (
          'name' => 'measure',
          'maxOccurs' => '1',
          'minOccurs' => '1',
          'dataType' => 'decimal',
          'totalDigits' => '16',
        ),
        1 => 
        array (
          'name' => 'unit',
          'maxOccurs' => '1',
          'minOccurs' => '1',
          'dataType' => 'string',
          'optionValues' => 
          array (
            0 => 'in',
            1 => 'cm',
          ),
        ),
      ),
    ),
    'legOpeningCut' => 
    array (
      'name' => 'legOpeningCut',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'How high on the body the leg opening sits. Commonly referenced for leotards, swimwear, underwear or other legless garments. ',
      'requiredLevel' => 'Optional',
      'displayName' => 'Leg Opening Cut',
      'group' => 'Lower Body Features',
      'rank' => '83000',
      'dataType' => 'string',
      'optionValues' => 
      array (
        0 => 'high-cut',
        1 => 'regular',
        2 => 'below hip',
        3 => 'at hip',
      ),
    ),
    'pantLegCut' => 
    array (
      'name' => 'pantLegCut',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Common style terms describing how the garment leg has been cut to make a specific sillhoutte/shape.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Pant Leg Cut',
      'group' => 'Lower Body Features',
      'rank' => '84000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'jeanStyle' => 
    array (
      'name' => 'jeanStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Style terms specific to jeans.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Jean Style',
      'group' => 'Lower Body Features',
      'rank' => '85000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'jeanWash' => 
    array (
      'name' => 'jeanWash',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Description of post-process wash treatment effecting the appearance of dye and fabric texture, specific to jeans.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Jean Wash',
      'group' => 'Lower Body Features',
      'rank' => '86000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'jeanFinish' => 
    array (
      'name' => 'jeanFinish',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Fabric finishes specific to jeans.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Jean Finish',
      'group' => 'Lower Body Features',
      'rank' => '87000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'pantSize' => 
    array (
      'name' => 'pantSize',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'A composite of Waist Size and Inseam. Do not fill in this attribute if you have separately filled in both "Waist Size" and "Inseam". If the pant size is in numbers (e.g. 12) or standard sizes (e.g. Large), enter the information under "Clothing Size".',
      'requiredLevel' => 'Optional',
      'displayName' => 'Pant Size',
      'group' => 'Lower Body Features',
      'rank' => '87500',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'pantFit' => 
    array (
      'name' => 'pantFit',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Terms that describe the way pants will fit when worn.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Pant Fit',
      'group' => 'Lower Body Features',
      'rank' => '88000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'pantStyle' => 
    array (
      'name' => 'pantStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Style terms specific to pants.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Pant Style',
      'group' => 'Lower Body Features',
      'rank' => '89000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'beltStyle' => 
    array (
      'name' => 'beltStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Styles specific to belts.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Belt Style',
      'group' => 'Lower Body Features',
      'rank' => '91000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'beltBuckleStyle' => 
    array (
      'name' => 'beltBuckleStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Belt buckle configurations.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Belt Buckle Style',
      'group' => 'Lower Body Features',
      'rank' => '92000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'pantyStyle' => 
    array (
      'name' => 'pantyStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Descriptive styles common to underwear bottoms and lower body elements of swimwear and leotards.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Underpant/Swim Bottom Style',
      'group' => 'Lower Body Features',
      'rank' => '93000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'shortsStyle' => 
    array (
      'name' => 'shortsStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Styles specific to shorts.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Shorts Style',
      'group' => 'Lower Body Features',
      'rank' => '94000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'skirtAndDressCut' => 
    array (
      'name' => 'skirtAndDressCut',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Terms describing a garment\'s skirt style, applicable to dresses and skirt products.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Skirt Style',
      'group' => 'Lower Body Features',
      'rank' => '95000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'skirtLengthStyle' => 
    array (
      'name' => 'skirtLengthStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Descriptive terms for length specific to skirts and dresses.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Skirt Length Style',
      'group' => 'Lower Body Features',
      'rank' => '96000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'hosieryStyle' => 
    array (
      'name' => 'hosieryStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Styles/features specific to tights and hosiery.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Hosiery Style',
      'group' => 'Lower Body Features',
      'rank' => '97000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'tightsSheerness' => 
    array (
      'name' => 'tightsSheerness',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Sheerness/opacities specific to tights and hosiery.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Sheerness',
      'group' => 'Lower Body Features',
      'rank' => '98000',
      'dataType' => 'string',
      'optionValues' => 
      array (
        0 => 'opaque',
        1 => 'semi-opaque',
        2 => 'sheer',
        3 => 'thick opaque',
        4 => 'ultra-sheer',
      ),
    ),
    'underwearStyle' => 
    array (
      'name' => 'underwearStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Descriptive styles specific to underwear.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Underwear Style',
      'group' => 'Lower Body Features',
      'rank' => '99000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'sockSize' => 
    array (
      'name' => 'sockSize',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Sock size. Generic sized (small/med/large) socks may not have this information (generic s/m/l size information should be entered under the clothing size attribute).',
      'requiredLevel' => 'Optional',
      'displayName' => 'Sock Size',
      'group' => 'Lower Body Features',
      'rank' => '100000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'sockStyle' => 
    array (
      'name' => 'sockStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Styles specific to socks. Does not include descriptive terms for sock height - those are in the Sock Rise attribute.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Sock Style',
      'group' => 'Lower Body Features',
      'rank' => '101000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'sockRise' => 
    array (
      'name' => 'sockRise',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Descriptive terms for sock height.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Sock Rise',
      'group' => 'Lower Body Features',
      'rank' => '102000',
      'dataType' => 'string',
      'optionValues' => 
      array (
        0 => 'thigh-high',
        1 => 'knee-high',
        2 => 'crew',
        3 => 'quarter',
        4 => 'low-cut',
        5 => 'no-show',
      ),
    ),
    'fabricContent' => 
    array (
      'name' => 'fabricContent',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Material makeup of the item.',
      'requiredLevel' => 'Recommended',
      'displayName' => 'Fabric Content',
      'group' => 'Additional Category Attributes',
      'rank' => '104000',
    ),
    'fabricCareInstructions' => 
    array (
      'name' => 'fabricCareInstructions',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Describes how the fabric should be cleaned. Enter details of the fabric care label found on the item. (For garments, typically located inside on the top of the back or the lower left side.)',
      'requiredLevel' => 'Recommended',
      'displayName' => 'Fabric Care Instructions',
      'group' => 'Additional Category Attributes',
      'rank' => '107000',
    ),
    'accentColor' => 
    array (
      'name' => 'accentColor',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'A secondary product color.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Accent Color',
      'group' => 'Additional Category Attributes',
      'rank' => '107500',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'clothingWeight' => 
    array (
      'name' => 'clothingWeight',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Commonly used in retail clothing, these terms describe the density or weight of fabric material.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Clothing Weight',
      'group' => 'Additional Category Attributes',
      'rank' => '108000',
      'dataType' => 'string',
      'optionValues' => 
      array (
        0 => 'lightweight',
        1 => 'mid-weight',
        2 => 'heavyweight',
      ),
    ),
    'clothingStyle' => 
    array (
      'name' => 'clothingStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Styles and designations that apply generally to various types of clothing.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Clothing Style',
      'group' => 'Additional Category Attributes',
      'rank' => '109000',
      'dataType' => 'string',
      'maxLength' => '200',
      'minLength' => '1',
    ),
    'clothingFit' => 
    array (
      'name' => 'clothingFit',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Terms that describe the way a garment will fit when worn. Does not include fit values specific to pants.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Clothing Fit',
      'group' => 'Additional Category Attributes',
      'rank' => '110000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'clothingCut' => 
    array (
      'name' => 'clothingCut',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Common clothing cut styles.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Clothing Cut',
      'group' => 'Additional Category Attributes',
      'rank' => '111000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'clothingLengthStyle' => 
    array (
      'name' => 'clothingLengthStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Descriptive terms for where on the lower-body a garment ends.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Clothing Length Style',
      'group' => 'Additional Category Attributes',
      'rank' => '112000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'fastenerType' => 
    array (
      'name' => 'fastenerType',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'The type of fastener used to keep a garment closed on the wearer and to facilitate putting on the garment.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Closure Type',
      'group' => 'Additional Category Attributes',
      'rank' => '113000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'swimsuitStyle' => 
    array (
      'name' => 'swimsuitStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Descriptive styles common to swimwear. Style terms specific to the bottom half of swimwear appear under the Underpant/Swim Bottom Style attribute.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Swimsuit Style',
      'group' => 'Additional Category Attributes',
      'rank' => '114000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'dressStyle' => 
    array (
      'name' => 'dressStyle',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Style terms specific to dresses. Other style terms that specifically describe a dress\'s skirt may be found under the Skirt Style attribute. Some values are shared between skirts and dresses: both "mini" dresses and "mini" skirts exist as separate products.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Dress Style',
      'group' => 'Additional Category Attributes',
      'rank' => '115000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'gotsCertification' => 
    array (
      'name' => 'gotsCertification',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Y indicates the product is certified under requirements of the Global Organic Textile Standard.',
      'requiredLevel' => 'Optional',
      'displayName' => 'GOTS Certification',
      'group' => 'Additional Category Attributes',
      'rank' => '116000',
      'dataType' => 'string',
      'optionValues' => 
      array (
        0 => 'Yes',
        1 => 'No',
      ),
    ),
    'theme' => 
    array (
      'name' => 'theme',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'A dominant idea, meaning, or setting applied to an item. Used in a wide range of products including decorative objects, clothing, toys, and furniture. Can be an important selection criteria for consumers who want to achieve a particular ambiance for room décor or for a special occasion.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Theme',
      'group' => 'Additional Category Attributes',
      'rank' => '117000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'character' => 
    array (
      'name' => 'character',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'A person or entity portrayed in print or visual media. A character might be a fictional personality or an actual living person.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Character',
      'group' => 'Additional Category Attributes',
      'rank' => '118000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'globalBrandLicense' => 
    array (
      'name' => 'globalBrandLicense',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'A brand name that is not owned by the product brand, but is licensed for the particular product. (Often character and media tie-ins and promotions.)',
      'requiredLevel' => 'Optional',
      'displayName' => 'Brand License',
      'group' => 'Additional Category Attributes',
      'rank' => '119000',
    ),
    'sportsLeague' => 
    array (
      'name' => 'sportsLeague',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'If your item has any association with a specific sports league, enter the league name. Abbreviations are fine. NOTE: This attribute flags an item for inclusion in the online fan shop.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Sports League',
      'group' => 'Additional Category Attributes',
      'rank' => '120000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'sportsTeam' => 
    array (
      'name' => 'sportsTeam',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'If your item has any association with a specific sports team, enter the team name. NOTE: This attribute flags an item for inclusion in the online fan shop.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Sports Team',
      'group' => 'Additional Category Attributes',
      'rank' => '121000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'occasion' => 
    array (
      'name' => 'occasion',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'The particular target time, event, or holiday for the product.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Occasion',
      'group' => 'Additional Category Attributes',
      'rank' => '124000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'activity' => 
    array (
      'name' => 'activity',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'The general type of activity one might perform while wearing this garment.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Activity',
      'group' => 'Additional Category Attributes',
      'rank' => '125000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'sport' => 
    array (
      'name' => 'sport',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'If the product is sports-related, the name of the specific sport depicted on the product, or the target sport for the product use',
      'requiredLevel' => 'Optional',
      'displayName' => 'Sport',
      'group' => 'Additional Category Attributes',
      'rank' => '126000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'season' => 
    array (
      'name' => 'season',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'If designed to be used during a specific type of year, the appropriate season this item may be used.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Season',
      'group' => 'Additional Category Attributes',
      'rank' => '127000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'weather' => 
    array (
      'name' => 'weather',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'The type of weather the clothing or fashion accessory was designed for.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Weather',
      'group' => 'Additional Category Attributes',
      'rank' => '128000',
      'dataType' => 'string',
      'maxLength' => '400',
      'minLength' => '1',
    ),
    'isMaternity' => 
    array (
      'name' => 'isMaternity',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Is this item marketed specifically to women who are pregnant?',
      'requiredLevel' => 'Optional',
      'displayName' => 'Is Maternity',
      'group' => 'Additional Category Attributes',
      'rank' => '129000',
      'dataType' => 'string',
      'optionValues' => 
      array (
        0 => 'Yes',
        1 => 'No',
      ),
    ),
    'academicInstitution' => 
    array (
      'name' => 'academicInstitution',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Name of College or other school. This is to distinguish the school from its sports team. ',
      'requiredLevel' => 'Recommended',
      'displayName' => 'Academic Institution',
      'group' => 'Additional Category Attributes',
      'rank' => '129250',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'athlete' => 
    array (
      'name' => 'athlete',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'A well-known athlete associated with a product, if applicable. This is used to group items in Fan Shop, not to describe a line of clothing.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Athlete',
      'group' => 'Nice to Have',
      'rank' => '129500',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'autographedBy' => 
    array (
      'name' => 'autographedBy',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'The full name of the person who has autographed this copy.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Autographed by',
      'group' => 'Nice to Have',
      'rank' => '129750',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'braBandSize' => 
    array (
      'name' => 'braBandSize',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'A measurement in inches of the band of the bra, which fits around the ribcage just under the bust. Use this if the garment has a band size only or to separate band and cup size for search discovery.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Bra Band Size',
      'group' => 'Nice to Have',
      'rank' => '130000',
      'child' => 
      array (
        0 => 
        array (
          'name' => 'measure',
          'maxOccurs' => '1',
          'minOccurs' => '1',
          'dataType' => 'decimal',
          'totalDigits' => '16',
        ),
        1 => 
        array (
          'name' => 'unit',
          'maxOccurs' => '1',
          'minOccurs' => '1',
          'dataType' => 'string',
          'optionValues' => 
          array (
            0 => 'in',
          ),
        ),
      ),
    ),
    'braCupSize' => 
    array (
      'name' => 'braCupSize',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'A letter size to optimize bra fit, calculated by measuring the chest at its widest point and subtracting the bra band size. 1 inch corresponds to 1 cup letter (e.g. if the difference is 5, the bra cup size is DD or E). Use this to record separate cup sizes for search discovery.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Bra Cup Size',
      'group' => 'Nice to Have',
      'rank' => '130500',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'neckSize' => 
    array (
      'name' => 'neckSize',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Neck size in inches.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Neck Size',
      'group' => 'Nice to Have',
      'rank' => '130750',
      'child' => 
      array (
        0 => 
        array (
          'name' => 'measure',
          'maxOccurs' => '1',
          'minOccurs' => '1',
          'dataType' => 'decimal',
          'totalDigits' => '16',
        ),
        1 => 
        array (
          'name' => 'unit',
          'maxOccurs' => '1',
          'minOccurs' => '1',
          'dataType' => 'string',
          'optionValues' => 
          array (
            0 => 'in',
          ),
        ),
      ),
    ),
    'sleeveLength' => 
    array (
      'name' => 'sleeveLength',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'The distance from the shoulder to the bottom hem of the sleeve, measured in inches.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Sleeve Length',
      'group' => 'Nice to Have',
      'rank' => '130875',
      'child' => 
      array (
        0 => 
        array (
          'name' => 'measure',
          'maxOccurs' => '1',
          'minOccurs' => '1',
          'dataType' => 'decimal',
          'totalDigits' => '16',
        ),
        1 => 
        array (
          'name' => 'unit',
          'maxOccurs' => '1',
          'minOccurs' => '1',
          'dataType' => 'string',
          'optionValues' => 
          array (
            0 => 'in',
          ),
        ),
      ),
    ),
    'inseam' => 
    array (
      'name' => 'inseam',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'For pants, the distance from the bottom of the leg to the seam in the crotch, measured in inches.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Inseam',
      'group' => 'Nice to Have',
      'rank' => '130968',
      'child' => 
      array (
        0 => 
        array (
          'name' => 'measure',
          'maxOccurs' => '1',
          'minOccurs' => '1',
          'dataType' => 'decimal',
          'totalDigits' => '16',
        ),
        1 => 
        array (
          'name' => 'unit',
          'maxOccurs' => '1',
          'minOccurs' => '1',
          'dataType' => 'string',
          'optionValues' => 
          array (
            0 => 'in',
          ),
        ),
      ),
    ),
    'isMadeFromRecycledMaterial' => 
    array (
      'name' => 'isMadeFromRecycledMaterial',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Indicates that the item is made from recycled materials.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Is Made From Recycled Material',
      'group' => 'Nice to Have',
      'rank' => '131000',
      'dataType' => 'string',
      'optionValues' => 
      array (
        0 => 'Yes',
        1 => 'No',
      ),
    ),
    'recycledMaterialContent' => 
    array (
      'name' => 'recycledMaterialContent',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'If item contains reused/recycled material, the percentage of all recycled material used to produce the item. This can also include specific material composition; cushions made from 30% recycled cotton fabric. Used to highlight sustainability to the customer.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Recycled Material Content',
      'group' => 'Nice to Have',
      'rank' => '132000',
    ),
    'features' => 
    array (
      'name' => 'features',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'List notable features of the item.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Additional Features',
      'group' => 'Nice to Have',
      'rank' => '143000',
    ),
    'keywords' => 
    array (
      'name' => 'keywords',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'documentation' => 'Words that people would use to search for this item. Keywords can include synonyms and related terms.',
      'requiredLevel' => 'Optional',
      'displayName' => 'Keywords',
      'group' => 'Nice to Have',
      'rank' => '144000',
      'dataType' => 'string',
      'maxLength' => '4000',
      'minLength' => '1',
    ),
    'swatchImages' => 
    array (
      'name' => 'swatchImages',
      'maxOccurs' => '1',
      'minOccurs' => '0',
      'child' => 
      array (
        0 => 
        array (
          'name' => 'swatchImage',
          'maxOccurs' => 'unbounded',
          'minOccurs' => '1',
          'child' => 
          array (
            0 => 
            array (
              'name' => 'swatchVariantAttribute',
              'maxOccurs' => '1',
              'minOccurs' => '1',
              'documentation' => 'Conditionally Required',
              'conditionalAttributes' => 
              array (
                0 => 
                array (
                  'name' => 'swatchImageUrl',
                  'value' => 'ANY',
                ),
              ),
              'displayName' => 'Swatch Variant Attribute',
              'group' => 'Item Variants',
              'dataType' => 'string',
              'optionValues' => 
              array (
                0 => 'color',
                1 => 'clothingSize',
                2 => 'clothingFit',
                3 => 'pattern',
                4 => 'material',
                5 => 'inseam',
                6 => 'waistSize',
                7 => 'neckSize',
                8 => 'hatSize',
                9 => 'pantySize',
                10 => 'sockSize',
                11 => 'countPerPack',
                12 => 'count',
                13 => 'braSize',
                14 => 'braBandSize',
                15 => 'braCupSize',
                16 => 'academicInstitution',
                17 => 'accentColor',
                18 => 'sportsTeam',
                19 => 'character',
              ),
            ),
            1 => 
            array (
              'name' => 'swatchImageUrl',
              'maxOccurs' => '1',
              'minOccurs' => '1',
              'documentation' => 'Conditionally Required',
              'conditionalAttributes' => 
              array (
                0 => 
                array (
                  'name' => 'swatchVariantAttribute',
                  'value' => 'ANY',
                ),
              ),
              'displayName' => 'Swatch Image URL',
              'group' => 'Item Variants',
              'dataType' => 'anyURI',
            ),
          ),
        ),
      ),
    ),
  ),
);